name: CreateRelease

on: 
    push:
        branches: '*'
        tags: v*
    pull_request:
        branches: [ master ]
        
jobs:
    Build_SetupCI:
        runs-on: ubuntu-latest
        outputs:
          artifactName: ${{ steps.outPutName.outputs.Name }}
          artifactPath: ${{ steps.outPutPath.outputs.Path }}
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: 'SetupCI'
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.110
            - name: Initialize modding environment
              uses: beat-forge/init-beatsaber@v1.1.0
              with:
                  token: ${{ github.token }}
                  version: 1.27.0
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{ github.workspace }}/PPPredictor/manifest.build.json
            - name: Build
              id: Build
              run: dotnet build --configuration Release
            #- name: Test
              #run: dotnet test --no-restore --verbosity normal
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.Build.outputs.filename }}
                  path: ${{ steps.Build.outputs.artifactpath }}
            - id: outPutName
              run: echo "Name=${{ steps.Build.outputs.filename }}" >> "$GITHUB_OUTPUT"
            - id: outPutPath
              run: echo "Path=${{ steps.Build.outputs.artifactpath }}" >> "$GITHUB_OUTPUT"

    Build_1_31_1:
            runs-on: ubuntu-latest
            outputs:
              artifactName: ${{ steps.outPutName.outputs.Name }}
              artifactPath: ${{ steps.outPutPath.outputs.Path }}
            steps:
                - uses: actions/checkout@v3
                  with:
                      ref: 'BS_1_31_1'
                - name: Setup dotnet
                  uses: actions/setup-dotnet@v3
                  with:
                      dotnet-version: 7.0.110
                - name: Initialize modding environment
                  uses: beat-forge/init-beatsaber@v1.1.0
                  with:
                      token: ${{ github.token }}
                      version: 1.31.1
                - name: Download Mod Dependencies
                  uses: Goobwabber/download-beatmods-deps@1.2
                  with:
                      manifest: ${{ github.workspace }}/PPPredictor/manifest.json
                - name: Build
                  id: Build
                  run: dotnet build --configuration Release
                #- name: Test
                  #run: dotnet test --no-restore --verbosity normal
                - name: GitStatus
                  run: git status
                - name: Echo Filename
                  run: echo $BUILDTEXT \($ASSEMBLYNAME\)
                  env:
                      BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                      ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
                - name: Upload Artifact
                  uses: actions/upload-artifact@v1
                  with:
                      name: ${{ steps.Build.outputs.filename }}
                      path: ${{ steps.Build.outputs.artifactpath }}
                - id: outPutName
                  run: echo "Name=${{ steps.Build.outputs.filename }}" >> "$GITHUB_OUTPUT"
                - id: outPutPath
                  run: echo "Path=${{ steps.Build.outputs.artifactpath }}" >> "$GITHUB_OUTPUT"

    start:
        name: Start
        needs: [Build_SetupCI, Build_1_31_1]
        runs-on: ubuntu-latest
        env:
              Build_SetupCI_ArtifactName: ${{ needs.Build_SetupCI.outputs.artifactName }}
              Build_SetupCI_ArtifactFile: ${{ needs.Build_SetupCI.outputs.artifactName }}.zip
              Build_1_31_1_ArtifactName: ${{ needs.Build_1_31_1.outputs.artifactName }}
              Build_1_31_1_ArtifactFile: ${{ needs.Build_1_31_1.outputs.artifactName }}.zip
        steps:
          - run: echo $Build_SetupCI_ArtifactName $Build_SetupCI_ArtifactFile
          - run: echo $Build_1_31_1_ArtifactName $Build_1_31_1_ArtifactFile
          - uses: actions/download-artifact@master
            with:
             name: ${{env.Build_SetupCI_ArtifactName}}
             path: ./artifact/Build_SetupCI
          - uses: actions/download-artifact@master
            with:
             name: ${{env.Build_1_31_1_ArtifactName}}
             path: ./artifact/Build_1_31_1
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
                files: |
                    ./artifact/Build_SetupCI/$Build_1_31_1_ArtifactFile
                    ./artifact/Build_1_31_1/$Build_1_31_1_ArtifactFile
                draft: true
            env: 
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
