name: CreateRelease

on: workflow_dispatch
jobs:
    BuildMaster:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: 'master'
            - name: Setup dotnet
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 7.0.110
            - name: Initialize modding environment
              uses: beat-forge/init-beatsaber@v1.1.0
              with:
                  token: ${{ github.token }}
                  version: 1.27.0
            - name: Download Mod Dependencies
              uses: Goobwabber/download-beatmods-deps@1.2
              with:
                  manifest: ${{ github.workspace }}/PPPredictor/manifest.build.json
            - name: Build
              id: Build
              run: dotnet build --configuration Release
            #- name: Test
              #run: dotnet test --no-restore --verbosity normal
            - name: GitStatus
              run: git status
            - name: Echo Filename
              run: echo $BUILDTEXT \($ASSEMBLYNAME\)
              env:
                  BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                  ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ${{ steps.Build.outputs.filename }}
                  path: ${{ steps.Build.outputs.artifactpath }}
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: ./${{ steps.Build.outputs.filename }}.zip
              env: 
                GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    Build_1_31_1:
            runs-on: ubuntu-latest
            steps:
                - uses: actions/checkout@v3
                  with:
                      ref: 'BS_1_31_1'
                - name: Setup dotnet
                  uses: actions/setup-dotnet@v3
                  with:
                      dotnet-version: 7.0.110
                - name: Initialize modding environment
                  uses: beat-forge/init-beatsaber@v1.1.0
                  with:
                      token: ${{ github.token }}
                      version: 1.31.1
                - name: Download Mod Dependencies
                  uses: Goobwabber/download-beatmods-deps@1.2
                  with:
                      manifest: ${{ github.workspace }}/PPPredictor/manifest.json
                - name: Build
                  id: Build
                  run: dotnet build --configuration Release
                #- name: Test
                  #run: dotnet test --no-restore --verbosity normal
                - name: GitStatus
                  run: git status
                - name: Echo Filename
                  run: echo $BUILDTEXT \($ASSEMBLYNAME\)
                  env:
                      BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                      ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
                - name: Upload Artifact
                  uses: actions/upload-artifact@v1
                  with:
                      name: ${{ steps.Build.outputs.filename }}
                      path: ${{ steps.Build.outputs.artifactpath }}
                - name: Release
                  uses: softprops/action-gh-release@v1
                  if: startsWith(github.ref, 'refs/tags/')
                  with:
                    files: ./${{ steps.Build.outputs.filename }}.zip
                  env: 
                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
